apiVersion: v1
kind: Service
metadata:
  name: {{ include "harness.fullname" . }}
  labels: {{- include "harness.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "harness.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: 9464
      targetPort: metrics
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "harness.fullname" . }}
  labels: {{- include "harness.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "harness.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
